namespace               = "ims"
mysql_service_name    = "mysql-k8s-services"
react_service_name      = "react-k8s-services"
springboot_service_name = "springboot-k8s-services"
frontend_image = "madhurmoms/inventory-management-frontend"
backend_image = "madhurmoms/inventory-management-backend"
